### ISSUE TITLE
[feature] option to maximize on startup only

### ISSUE THREAD

**Issue by atomGit** [ericchase/maximize-all-windows#1]
this is a good idea that can solve a problem many FF users have when `privacy.resistFingerprinting` is enabled - one of the things this pref does is to cause FF to select a generic window size when started in order to make fingerprinting harder

seems a lot of people don't like that and i'm one of them

however, that's the only thing i want to do - maximize the 'normal' FF window on startup - and so i'm wondering if you could might add an option to do only that, or create a minimal version without the extra functions and options page?

**Comment by ericchase** [comment]
Hello!

So, the options page is gonna be there either way, except for the extra stuff I put on the bottom. I decided to make startup option checked by default. There are no other functions right now, except for the browser action, which can be remove by customizing.

The options page should not affect anything. Is there any reason it might bother you?
As for the browser action (icon), is removing it manually not enough?

Give me any more details you can. I don't know too much about the finger printing stuff.
Eric
On 5/2/2019 7:43:30 AM, atomGit <notifications@github.com> wrote:
this is a good idea that can solve a problem many FF users have when privacy.resistFingerprinting is enabled - one of the things this pref does is to cause FF to select a generic window size when started in order to make fingerprinting harder
seems a lot of people don't like that and i'm one of them
however, that's the only thing i want to do - maximize the 'normal' FF window on startup - and so i'm wondering if you could might add an option to do only that, or create a minimal version without the extra functions and options page?

**Comment by ericchase** [comment]
Just realized that I never updated the readme with the link to the store page. Haha, please try it out and let me know what you would like different.

**Comment by atomGit** [comment]
my only interest is to use as little resources as possible - i'm not a developer, but i thought that maybe the 'add listener' stuff for anything other than the main FF window might be using CPU cycles ??? - if that is not the case, then the ext. is fine as it is and you can close this issue if you like

as for fingerprinting, don't worry about it - users should be aware of the increased entropy if they run FF maximized and that's on them - personally i'm OK with that, which is why i like this add-on - my OS (Linux, KDE) has options for window management and i've been using that to try and force FF to maximize on start, but it's unreliable - your ext. seems to work every time because it's apparently loaded after FF loads the RFP (resist fingerprinting) code

thanks! much appreciated

**Comment by ericchase** [comment]
No problem! As far as the performance, the code is extremely minimal. I have no clue how the browser handles listeners for extensions. I imagine it adds some trace amount of overhead, which is inefficient if you never have to click the icon. In short, you *could* save some resources by disabling the stuff you mentioned. How much is anyone's guess.

**Comment by ericchase** [comment]
Give me a bit, and I'll publish a *slimmed down* version.

**Comment by atomGit** [comment]
oh wow - thanks!
i'd suggest dropping the icons, the option to max on startup (just hard-code that) and anything else you can :)

**Comment by ericchase** [comment]
And it's ready.

https://addons.mozilla.org/en-US/firefox/addon/maximize-all-windows-minimal/

**Comment by atomGit** [comment]
perfection! was gonna see about forking this one if i couldn't social engineer you to do the work LOL :)

i added a link on my tweaks and stuff page [here](https://12bytes.org/articles/tech/firefox/firefox-tweaks-and-fixes-and-things#firefox_doesnt_remember_its_window_size_after_restart) (i'll update it in a min. to point to the minimal version)

thanks!
